house/urls.py
# coding: utf-8

from django.conf.urls import url, include
from django.contrib import admin
from website.views import home
from web.views import index
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    # 首页
    url(r'^', include('website.urls', namespace='website')),
    # 管理员后台
    url(r'^admin/', include('web.urls', namespace='web')),
    url(r'^h5$', TemplateView.as_view(template_name='longpage.html')),
    url(r'^h5/houses/$', TemplateView.as_view(template_name='index.html')),
    url(r'^wechatapi/', include('wechatapi.urls', namespace='wechatapi')),
    # 超级后台
    url(r'^superadmin/', admin.site.urls),
    url(r'^MP_verify_Dh0tQXMmIg6fVOq9.txt', index.validation),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}), 
]

web/urls.py
# coding: utf-8

from django.conf.urls import url

from web.views import (
    index,
    auth,
    column,
    home,
    venture_manage,
    permissions,
    operating,
    infrastructure,
    user,
    flush,
    listings,
    wanted,
    listings_release,
    wanted_release,
    acl,
    group,
    house_demand
)

# 管理后台
urlpatterns = [
    # 首页
    url(r'^$', index.index, name='admin_index'),
    # 登陆注册
    url(r'^login$', auth.login_view, name='admin_login'),
    url(r'^logout$', auth.logout_view, name='admin_logout'),
    url(r'^uptoken/$', index.uptoken, name='admin_uptoken'),

    url(r'^flush/setting/$', flush.setting, name='flush_setting'),

    url(r'^acl$', acl.list, name='acl_list'),
    url(r'^acl/add$', acl.add, name='acl_add'),
    url(r'^acl/(?P<acl_id>\d+)/edit$', acl.edit, name='acl_edit'),
    url(r'^acl/(?P<acl_id>\d+)/delete$', acl.delete, name='acl_delete'),

    url(r'^group$', group.list, name='group_list'),
    url(r'^group/add$', group.add, name='group_add'),
    url(r'^group/(?P<group_id>\d+)/edit$',
        group.edit, name='group_edit'),
    url(r'^group/(?P<group_id>\d+)/delete$',
        group.delete, name='group_delete'),

    # 轮播
    url(r'^advertising/list/$', home.advertising_list, name='advertising_list'),
    url(r'^advertising/create$',
        home.advertising_create,
        name='advertising_create'),
    url(r'^advertising/(?P<advertising_id>\d+)/edit$',
        home.advertising_edit, name='advertising_edit'),
    url(r'^advertising/(?P<advertising_id>\d+)/delete$',
        home.advertising_delete, name='advertising_delete'),
    url(r'^advertising/(?P<advertising_id>\d+)/up/$',
        home.advertising_up, name='advertising_up'),
    url(r'^advertising/(?P<advertising_id>\d+)/down/$',
        home.advertising_down, name='advertising_down'),

    # 栏目
    url(r'^column/list/$', column.list, name='column_list'),
    url(r'^column/create$', column.create, name='column_create'),
    url(r'^column/(?P<column_id>\d+)/edit$', column.edit, name='column_edit'),
    url(r'^column/(?P<column_id>\d+)/delete$',
        column.delete, name='column_delete'),
    url(r'^column/(?P<column_id>\d+)/up/$', column.up, name='column_up'),
    url(r'^column/(?P<column_id>\d+)/down/$', column.down, name='column_down'),

    # 用户管理
    url(r'^user/list/$', user.list, name='user_list'),
    url(r'^user/(?P<profile_id>\d+)/online/$',
        user.online, name='user_online'),
    url(r'^user/(?P<profile_id>\d+)/offline/$',
        user.offline, name='user_offline'),

    # 基础设施
    url(r'^infrastructure/list/$',
        infrastructure.list,
        name='infrastructure_list'),
    url(r'^infrastructure/create$',
        infrastructure.create,
        name='infrastructure_create'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/edit$',
        infrastructure.edit, name='infrastructure_edit'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/delete$',
        infrastructure.delete, name='infrastructure_delete'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/up/$',
        infrastructure.up, name='infrastructure_up'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/down/$',
        infrastructure.down, name='infrastructure_down'),

    # 房源列表
    url(r'^listings/list/$', listings.list, name='listings_list'),
    url(r'^listings/create/$',
        listings.create, name='listings_create'),
    url(r'^listings/(?P<housingresources_id>\d+)/edit/$',
        listings.edit, name='listings_edit'),
    url(r'^listings/(?P<housingresources_id>\d+)/online$',
        listings.online, name='listings_online'),
    url(r'^listings/(?P<housingresources_id>\d+)/offline$',
        listings.offline, name='listings_offline'),
    url(r'^listings/(?P<housingresources_id>\d+)/onquality$',
        listings.onquality, name='listings_onquality'),
    url(r'^listings/(?P<housingresources_id>\d+)/offquality$',
        listings.offquality, name='listings_offquality'),

    # 房源预约
    url(r'^listings/meet/list/$', listings.meet_list, name='listings_meet_list'),
    url(r'^listings/meet/(?P<housingresources_meet_id>\d+)/delete$', listings.meet_delete, name='listings_meet_delete'),
    url(r'^listings/meet/(?P<housingresources_meet_id>\d+)/complete$', listings.meet_complete, name='listings_meet_complete'),

    url(r'^listings/(?P<housingresources_id>\d+)/delete$',
        listings.delete, name='listings_delete'),
    # 房源图片
    url(r'^listings/(?P<housingresources_id>\d+)/picture/list/$',
        listings.picture_list,
        name='listings_picture_list'),
    url(r'^listings/(?P<housingresources_id>\d+)/picture/create/$',
        listings.picture_create, name='listings_picture_create'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/edit/$',
        listings.picture_edit, name='listings_picture_edit'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/delete$',
        listings.picture_delete, name='listings_picture_delete'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/up$',
        listings.picture_up, name='listings_picture_up'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/down$',
        listings.picture_down, name='listings_picture_down'),
    # 房源卧室
    url(r'^listings/(?P<housingresources_id>\d+)/bedroom/list/$',
        listings.bedroom_list,
        name='listings_bedroom_list'),
    url(r'^listings/(?P<housingresources_id>\d+)/bedroom/create/$',
        listings.bedroom_create, name='listings_bedroom_create'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/edit/$',
        listings.bedroom_edit, name='listings_bedroom_edit'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/delete$',
        listings.bedroom_delete, name='listings_bedroom_delete'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/online$',
        listings.bedroom_online, name='listings_bedroom_online'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/offline$',
        listings.bedroom_offline, name='listings_bedroom_offline'),


    # 房源发布
    url(r'^listings_release/list/$',
        listings_release.list,
        name='listings_release_list'),
    url(r'^listings_release/(?P<housingresources_id>\d+)/online/$',
        listings_release.online, name='listings_release_online'),
    url(r'^listings_release/(?P<housingresources_id>\d+)/offline/$',
        listings_release.offline, name='listings_release_offline'),

    # 求租列表
    url(r'^wanted/list/$', wanted.list, name='wanted_list'),
    url(r'^wanted/(?P<renthouse_id>\d+)/online$',
        wanted.online, name='wanted_online'),
    url(r'^wanted/(?P<renthouse_id>\d+)/offline$',
        wanted.offline, name='wanted_offline'),
    url(r'^wanted/(?P<renthouse_id>\d+)/delete$',
        wanted.delete, name='wanted_delete'),
    url(r'^wanted/import_data$', wanted.import_data, name='wanted_import_data'),
    # 求租预约
    url(r'^wanted/meet/list/$', wanted.meet_list, name='wanted_meet_list'),
    url(r'^wanted/meet/(?P<renthouse_meet_id>\d+)/delete$', wanted.meet_delete, name='wanted_meet_delete'),
    url(r'^wanted/meet/(?P<renthouse_meet_id>\d+)/complete$', wanted.meet_complete, name='wanted_meet_complete'),

    # 求租发布审核
    url(r'^wanted_release/list/$',
        wanted_release.list,
        name='wanted_release_list'),
    url(r'^wanted_release/(?P<renthouse_id>\d+)/online/$',
        wanted_release.online, name='wanted_release_online'),
    url(r'^wanted_release/(?P<renthouse_id>\d+)/offline/$',
        wanted_release.offline, name='wanted_release_offline'),

    # 租房需求
    url(r'^house_demand/list/$', house_demand.list, name='house_demand_list'),

    # 商家管理员
    url(r'^venture_manage/list$',
        venture_manage.venture_manage_list,
        name='venture_manage_list'),
    url(r'^venture_manage/create$',
        venture_manage.venture_manage_create,
        name='venture_manage_create'),
    url(r'^venture_manage/(?P<account_id>\d+)/edit$',
        venture_manage.venture_manage_edit,
        name='venture_manage_edit'),
    url(r'^venture_manage/(?P<account_id>\d+)/delete$',
        venture_manage.venture_manage_delete,
        name='venture_manage_delete'),

    # 权限组
    url(r'^permissions/list$',
        permissions.permissions_list,
        name='permissions_list'),
    url(r'^permissions/create$',
        permissions.permissions_create,
        name='permissions_create'),
    url(r'^permissions/(?P<permissions_id>\d+)/edit$',
        permissions.permissions_edit, name='permissions_edit'),
    url(r'^permissions/(?P<permissions_id>\d+)/delete$',
        permissions.permissions_delete, name='permissions_delete'),

    # 系统管理员
    url(r'^operating/list$', operating.operating_list, name='operating_list'),
    url(r'^operating/create$',
        operating.operating_create,
        name='operating_create'),
    url(r'^operating/(?P<operating_id>\d+)/edit$',
        operating.operating_edit, name='operating_edit'),
    url(r'^operating/(?P<operating_id>\d+)/delete$',
        operating.operating_delete, name='operating_delete'),

    # 上传文件
    url(r'^ckeditor_upload$', index.ckeditor_upload, name='admin_upload'),
    url(r'^ckeditor_many_upload$',
        index.ckeditor_many_upload,
        name='admin_many_upload'),
]

website/urls.py
# coding: utf-8

from django.conf.urls import url

from website.views import (
    home,
    user,
    rent_house,
)

# 管理后台
urlpatterns = [
    # 首页
    url(r'^$', home.index, name='home_index'),
    url(r'^search$', home.search, name='home_search'),
    url(r'^captcha/$', home.captcha, name='captcha'),
    url(r'^register$', home.register, name='home_register'),
    url(r'^login$', home.login, name='home_login'),
    url(r'^feedback/add$', home.feedback_add, name='home_feedback_add'),
    url(r'^upload_file$', home.upload_file, name='upload_file'),
    url(r'^send/vcode$', home.send_vcode, name='send_vcode'),
    url(r'^send/vcode1$', home.send_vcode1, name='send_vcode1'),

    # 房源
    url(r'^housing_resources$',
        home.housing_resources_list, name='housing_resources_list'),
    url(r'^housing_resources_map$',
        home.housing_resources_map_list, name='housing_resources_map_list'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)$',
        home.housing_resources, name='housing_resources'),
    url(r'^housing_resources/meet/create$',
        home.housing_resources_meet_create, name='housing_resources_meet_create'),

    # 求租
    url(r'^rent_house$',
        rent_house.rent_house_list, name='rent_house_list'),
    url(r'^rent_house/meet/create$',
        rent_house.rent_house_meet_create, name='rent_house_meet_create'),

    # 用户
    url(r'^user$', user.index, name='user_index'),
    url(r'^user/update_profile$', user.update_profile, name='update_profile'),
    url(r'^user/update_avatar$', user.update_avatar, name='update_avatar'),
    url(r'^login_out$', user.login_out, name='login_out'),
    url(r'^reset/pwd$', user.reset_pwd, name='reset_pwd'),

    # 房源发布
    url(r'^housing_resources/create$',
        user.housing_resource_create,
        name='housing_resource_create'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)/edit$',
        user.housing_resource_edit, name='housing_resource_edit'),
    url(r'^user/housing_resources$',
        user.housing_resources,
        name='user_housing_resources'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)/offline$',
        user.housing_resource_offline, name='housing_resource_offline'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)/online$',
        user.housing_resource_online, name='housing_resource_online'),

    # 求租发布
    url(r'^rent_house/create$',
        user.rent_house_create,
        name='rent_house_create'),
    url(r'^rent_house/(?P<rent_house_id>\d+)/edit$',
        user.rent_house_edit, name='rent_house_edit'),
    url(r'^user/rent_houses$',
        user.rent_house,
        name='user_rent_house'),
]

web/templates/super/housing/listings/list.html
{% extends 'super/base.html' %}

{% block pageheader %}
房源列表
{% endblock %}

{% block mainbody %}
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">
      房源列表
    </h3>
    <div class="box-tools">
    </div>
  </div><!-- /.box-header -->

  <div class="box-body">
    <div style="margin-bottom:15px;" class="row">
      <form class="navbar-form navbar-left" method="GET" role="search">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" name="search_name" placeholder="手机号" value="{{ search_name }}"/>
          </div>
          <div class="input-group">
            <input type="text" class="form-control" name="search_start" placeholder="开始时间" value="{{ search_start }}" id="search_start"/>
          </div>
          <div class="input-group">
            <input type="text" class="form-control" name="search_end" placeholder="结束时间" value="{{ search_end }}" id="search_end"/>
          </div>
          <select class="form-control" name="search_lease">
              <option value="-1" >选择租赁方式</option>
              <option value="0" {% if not search_lease %} selected {% endif %}>整租</option>
              <option value="1" {% if search_lease == 1 %} selected {% endif %}>合租</option>
          </select>
          <select class="form-control" name="search_status">
              <option value="-1">选择状态</option>
              <option value="0" {% if not search_status %} selected {% endif %}>下线</option>
              <option value="1" {% if search_status == 1 %} selected {% endif %}>上线</option>
          </select>
          <button type="submit" class="btn btn-info">搜索</button>
          <a class="btn btn-default" href="{% url 'web:listings_list' %}">清除</a>
          <a href="{% url 'web:listings_create' %}" class="btn btn-info">新建</a>
        </div>
      </form>
    </div>
    <div class="row">
      <div class="col-md-12">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <th style="width: 10px">#</th>
              <th>手机号</th>
              <th>房屋类型</th>
              <th>租赁方式</th>
              <th>押付方式</th>
              <th>所在小区</th>
              <th>房屋照片</th>
              <th>状态</th>
              <th>品质房源</th>
              <th>创建时间</th>
              <th>操作</th>
            </tr>
            {% for c in clients %}
              <tr>
                <td style="vertical-align: middle;">{{ c.id }}</td>
                <td style="vertical-align: middle;">{{ c.user.profile.mobile }}</td>
                <td style="vertical-align: middle;">{{ c.category }}</td>
                <td style="vertical-align: middle;">{{ c.get_lease_display }}</td>
                <td style="vertical-align: middle;">押{{ c.bet }}付{{ c.pay }}</td>
                <td style="vertical-align: middle;">{{ c.community }}</td>
                <td style="vertical-align: middle;">
                  <img src="{{ c.cover_url }}" width="50" height="50" />
                </td>
                <td style="vertical-align: middle;">{{ c.get_status_display }}</td>
                <td style="vertical-align: middle;">
                  {% if c.quality %}
                    <i class="fa fa-fw fa-check-circle text-green"></i>
                  {% else %}
                    <i class="fa fa-fw fa-ban text-red"></i>
                  {% endif %}
                </td>
                <td style="vertical-align: middle;">{{ c.created|date:"Y-m-d H:i" }}</td>
                <td style="vertical-align: middle;">
                    <a class="btn-xs btn-success" target="_blank" href="{% url 'website:housing_resources' c.id %}">预览</a>
                    <a class="btn-xs btn-info" href="{% url 'web:listings_bedroom_list' c.id %}">卧室管理</a>
                    <a class="btn-xs btn-info" href="{% url 'web:listings_picture_list' c.id %}">房源图片</a>
                    <a class="btn-xs btn-info" href="{% url 'web:listings_edit' c.id %}">编辑</a>
                    {% if not c.quality %}
                      <a class="btn-xs btn-success" href="{% url 'web:listings_onquality' c.id %}">
                        设为品质房源
                      </a>
                    {% else %}
                      <a class="btn-xs btn-warning" href="{% url 'web:listings_offquality' c.id %}">
                        取消品质房源
                      </a>
                    {% endif %}

                    {% if not c.status or c.status == 1 %}
                      <a class="btn-xs btn-success" href="{% url 'web:listings_online' c.id %}?page={{page}}">上线</a>
                    {% else %}
                      <a class="btn-xs btn-success" href="{% url 'web:listings_offline' c.id %}?page={{page}}">下线</a>
                    {% endif %}
                    <a class="btn-xs btn-danger" href="{% url 'web:listings_delete' c.id %}" onclick="return confirm('确认删除吗?')">
                      删除
                    </a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% with clients as paging_objs %}
      {% include 'super/paging.html' %}
    {% endwith %}
  </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  $(function(){
    $('#search_start, #search_end').datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      todayBtn: true,
    });
  })
</script>
{% endblock %}