house/urls.py
# coding: utf-8

from django.conf.urls import url, include
from django.contrib import admin
from website.views import home
from web.views import index
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    # 首页
    url(r'^', include('website.urls', namespace='website')),
    # 管理员后台
    url(r'^admin/', include('web.urls', namespace='web')),
    url(r'^h5$', TemplateView.as_view(template_name='longpage.html')),
    url(r'^h5/houses/$', TemplateView.as_view(template_name='index.html')),
    url(r'^wechatapi/', include('wechatapi.urls', namespace='wechatapi')),
    # 超级后台
    url(r'^superadmin/', admin.site.urls),
    url(r'^MP_verify_Dh0tQXMmIg6fVOq9.txt', index.validation),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}), 
]

web/urls.py
# coding: utf-8

from django.conf.urls import url

from web.views import (
    index,
    auth,
    column,
    home,
    venture_manage,
    permissions,
    operating,
    infrastructure,
    user,
    flush,
    listings,
    wanted,
    listings_release,
    wanted_release,
    acl,
    group,
    house_demand
)

# 管理后台
urlpatterns = [
    # 首页
    url(r'^$', index.index, name='admin_index'),
    # 登陆注册
    url(r'^login$', auth.login_view, name='admin_login'),
    url(r'^logout$', auth.logout_view, name='admin_logout'),
    url(r'^uptoken/$', index.uptoken, name='admin_uptoken'),

    url(r'^flush/setting/$', flush.setting, name='flush_setting'),

    url(r'^acl$', acl.list, name='acl_list'),
    url(r'^acl/add$', acl.add, name='acl_add'),
    url(r'^acl/(?P<acl_id>\d+)/edit$', acl.edit, name='acl_edit'),
    url(r'^acl/(?P<acl_id>\d+)/delete$', acl.delete, name='acl_delete'),

    url(r'^group$', group.list, name='group_list'),
    url(r'^group/add$', group.add, name='group_add'),
    url(r'^group/(?P<group_id>\d+)/edit$',
        group.edit, name='group_edit'),
    url(r'^group/(?P<group_id>\d+)/delete$',
        group.delete, name='group_delete'),

    # 轮播
    url(r'^advertising/list/$', home.advertising_list, name='advertising_list'),
    url(r'^advertising/create$',
        home.advertising_create,
        name='advertising_create'),
    url(r'^advertising/(?P<advertising_id>\d+)/edit$',
        home.advertising_edit, name='advertising_edit'),
    url(r'^advertising/(?P<advertising_id>\d+)/delete$',
        home.advertising_delete, name='advertising_delete'),
    url(r'^advertising/(?P<advertising_id>\d+)/up/$',
        home.advertising_up, name='advertising_up'),
    url(r'^advertising/(?P<advertising_id>\d+)/down/$',
        home.advertising_down, name='advertising_down'),

    # 栏目
    url(r'^column/list/$', column.list, name='column_list'),
    url(r'^column/create$', column.create, name='column_create'),
    url(r'^column/(?P<column_id>\d+)/edit$', column.edit, name='column_edit'),
    url(r'^column/(?P<column_id>\d+)/delete$',
        column.delete, name='column_delete'),
    url(r'^column/(?P<column_id>\d+)/up/$', column.up, name='column_up'),
    url(r'^column/(?P<column_id>\d+)/down/$', column.down, name='column_down'),

    # 用户管理
    url(r'^user/list/$', user.list, name='user_list'),
    url(r'^user/(?P<profile_id>\d+)/online/$',
        user.online, name='user_online'),
    url(r'^user/(?P<profile_id>\d+)/offline/$',
        user.offline, name='user_offline'),

    # 基础设施
    url(r'^infrastructure/list/$',
        infrastructure.list,
        name='infrastructure_list'),
    url(r'^infrastructure/create$',
        infrastructure.create,
        name='infrastructure_create'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/edit$',
        infrastructure.edit, name='infrastructure_edit'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/delete$',
        infrastructure.delete, name='infrastructure_delete'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/up/$',
        infrastructure.up, name='infrastructure_up'),
    url(r'^infrastructure/(?P<infrastructure_id>\d+)/down/$',
        infrastructure.down, name='infrastructure_down'),

    # 房源列表
    url(r'^listings/list/$', listings.list, name='listings_list'),
    url(r'^listings/create/$',
        listings.create, name='listings_create'),
    url(r'^listings/(?P<housingresources_id>\d+)/edit/$',
        listings.edit, name='listings_edit'),
    url(r'^listings/(?P<housingresources_id>\d+)/online$',
        listings.online, name='listings_online'),
    url(r'^listings/(?P<housingresources_id>\d+)/offline$',
        listings.offline, name='listings_offline'),
    url(r'^listings/(?P<housingresources_id>\d+)/onquality$',
        listings.onquality, name='listings_onquality'),
    url(r'^listings/(?P<housingresources_id>\d+)/offquality$',
        listings.offquality, name='listings_offquality'),

    # 房源预约
    url(r'^listings/meet/list/$', listings.meet_list, name='listings_meet_list'),
    url(r'^listings/meet/(?P<housingresources_meet_id>\d+)/delete$', listings.meet_delete, name='listings_meet_delete'),
    url(r'^listings/meet/(?P<housingresources_meet_id>\d+)/complete$', listings.meet_complete, name='listings_meet_complete'),

    url(r'^listings/(?P<housingresources_id>\d+)/delete$',
        listings.delete, name='listings_delete'),
    # 房源图片
    url(r'^listings/(?P<housingresources_id>\d+)/picture/list/$',
        listings.picture_list,
        name='listings_picture_list'),
    url(r'^listings/(?P<housingresources_id>\d+)/picture/create/$',
        listings.picture_create, name='listings_picture_create'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/edit/$',
        listings.picture_edit, name='listings_picture_edit'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/delete$',
        listings.picture_delete, name='listings_picture_delete'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/up$',
        listings.picture_up, name='listings_picture_up'),
    url(r'^listings/picture/(?P<housingpicture_id>\d+)/down$',
        listings.picture_down, name='listings_picture_down'),
    # 房源卧室
    url(r'^listings/(?P<housingresources_id>\d+)/bedroom/list/$',
        listings.bedroom_list,
        name='listings_bedroom_list'),
    url(r'^listings/(?P<housingresources_id>\d+)/bedroom/create/$',
        listings.bedroom_create, name='listings_bedroom_create'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/edit/$',
        listings.bedroom_edit, name='listings_bedroom_edit'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/delete$',
        listings.bedroom_delete, name='listings_bedroom_delete'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/online$',
        listings.bedroom_online, name='listings_bedroom_online'),
    url(r'^listings/bedroom/(?P<bedroom_id>\d+)/offline$',
        listings.bedroom_offline, name='listings_bedroom_offline'),


    # 房源发布
    url(r'^listings_release/list/$',
        listings_release.list,
        name='listings_release_list'),
    url(r'^listings_release/(?P<housingresources_id>\d+)/online/$',
        listings_release.online, name='listings_release_online'),
    url(r'^listings_release/(?P<housingresources_id>\d+)/offline/$',
        listings_release.offline, name='listings_release_offline'),

    # 求租列表
    url(r'^wanted/list/$', wanted.list, name='wanted_list'),
    url(r'^wanted/(?P<renthouse_id>\d+)/online$',
        wanted.online, name='wanted_online'),
    url(r'^wanted/(?P<renthouse_id>\d+)/offline$',
        wanted.offline, name='wanted_offline'),
    url(r'^wanted/(?P<renthouse_id>\d+)/delete$',
        wanted.delete, name='wanted_delete'),
    url(r'^wanted/import_data$', wanted.import_data, name='wanted_import_data'),
    # 求租预约
    url(r'^wanted/meet/list/$', wanted.meet_list, name='wanted_meet_list'),
    url(r'^wanted/meet/(?P<renthouse_meet_id>\d+)/delete$', wanted.meet_delete, name='wanted_meet_delete'),
    url(r'^wanted/meet/(?P<renthouse_meet_id>\d+)/complete$', wanted.meet_complete, name='wanted_meet_complete'),

    # 求租发布审核
    url(r'^wanted_release/list/$',
        wanted_release.list,
        name='wanted_release_list'),
    url(r'^wanted_release/(?P<renthouse_id>\d+)/online/$',
        wanted_release.online, name='wanted_release_online'),
    url(r'^wanted_release/(?P<renthouse_id>\d+)/offline/$',
        wanted_release.offline, name='wanted_release_offline'),

    # 租房需求
    url(r'^house_demand/list/$', house_demand.list, name='house_demand_list'),

    # 商家管理员
    url(r'^venture_manage/list$',
        venture_manage.venture_manage_list,
        name='venture_manage_list'),
    url(r'^venture_manage/create$',
        venture_manage.venture_manage_create,
        name='venture_manage_create'),
    url(r'^venture_manage/(?P<account_id>\d+)/edit$',
        venture_manage.venture_manage_edit,
        name='venture_manage_edit'),
    url(r'^venture_manage/(?P<account_id>\d+)/delete$',
        venture_manage.venture_manage_delete,
        name='venture_manage_delete'),

    # 权限组
    url(r'^permissions/list$',
        permissions.permissions_list,
        name='permissions_list'),
    url(r'^permissions/create$',
        permissions.permissions_create,
        name='permissions_create'),
    url(r'^permissions/(?P<permissions_id>\d+)/edit$',
        permissions.permissions_edit, name='permissions_edit'),
    url(r'^permissions/(?P<permissions_id>\d+)/delete$',
        permissions.permissions_delete, name='permissions_delete'),

    # 系统管理员
    url(r'^operating/list$', operating.operating_list, name='operating_list'),
    url(r'^operating/create$',
        operating.operating_create,
        name='operating_create'),
    url(r'^operating/(?P<operating_id>\d+)/edit$',
        operating.operating_edit, name='operating_edit'),
    url(r'^operating/(?P<operating_id>\d+)/delete$',
        operating.operating_delete, name='operating_delete'),

    # 上传文件
    url(r'^ckeditor_upload$', index.ckeditor_upload, name='admin_upload'),
    url(r'^ckeditor_many_upload$',
        index.ckeditor_many_upload,
        name='admin_many_upload'),
]

website/urls.py
# coding: utf-8

from django.conf.urls import url

from website.views import (
    home,
    user,
    rent_house,
)

# 管理后台
urlpatterns = [
    # 首页
    url(r'^$', home.index, name='home_index'),
    url(r'^search$', home.search, name='home_search'),
    url(r'^captcha/$', home.captcha, name='captcha'),
    url(r'^register$', home.register, name='home_register'),
    url(r'^login$', home.login, name='home_login'),
    url(r'^feedback/add$', home.feedback_add, name='home_feedback_add'),
    url(r'^upload_file$', home.upload_file, name='upload_file'),
    url(r'^send/vcode$', home.send_vcode, name='send_vcode'),
    url(r'^send/vcode1$', home.send_vcode1, name='send_vcode1'),

    # 房源
    url(r'^housing_resources$',
        home.housing_resources_list, name='housing_resources_list'),
    url(r'^housing_resources_map$',
        home.housing_resources_map_list, name='housing_resources_map_list'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)$',
        home.housing_resources, name='housing_resources'),
    url(r'^housing_resources/meet/create$',
        home.housing_resources_meet_create, name='housing_resources_meet_create'),

    # 求租
    url(r'^rent_house$',
        rent_house.rent_house_list, name='rent_house_list'),
    url(r'^rent_house/meet/create$',
        rent_house.rent_house_meet_create, name='rent_house_meet_create'),

    # 用户
    url(r'^user$', user.index, name='user_index'),
    url(r'^user/update_profile$', user.update_profile, name='update_profile'),
    url(r'^user/update_avatar$', user.update_avatar, name='update_avatar'),
    url(r'^login_out$', user.login_out, name='login_out'),
    url(r'^reset/pwd$', user.reset_pwd, name='reset_pwd'),

    # 房源发布
    url(r'^housing_resources/create$',
        user.housing_resource_create,
        name='housing_resource_create'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)/edit$',
        user.housing_resource_edit, name='housing_resource_edit'),
    url(r'^user/housing_resources$',
        user.housing_resources,
        name='user_housing_resources'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)/offline$',
        user.housing_resource_offline, name='housing_resource_offline'),
    url(r'^housing_resources/(?P<housing_resources_id>\d+)/online$',
        user.housing_resource_online, name='housing_resource_online'),

    # 求租发布
    url(r'^rent_house/create$',
        user.rent_house_create,
        name='rent_house_create'),
    url(r'^rent_house/(?P<rent_house_id>\d+)/edit$',
        user.rent_house_edit, name='rent_house_edit'),
    url(r'^user/rent_houses$',
        user.rent_house,
        name='user_rent_house'),
]

website/views/rent_house.py
# coding: utf-8

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.db.models import Q, Avg
from django.template import loader

from django.contrib.auth import login, logout, authenticate
from django.contrib.admin.views.decorators import staff_member_required
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
from web.models import(
    Profile,
    RentHouse,
    RentHouseMeet
)

from settings import (
    REDIS_HOST,
    REDIS_PORT,
    REDIS_DB,
    DB_PREFIX,
    UPLOAD_DIR,
    DOMAIN,
    QQ_MAP_API_URL
)

import os
import datetime
import time
import simplejson
import requests
import random
import string
import redis
import logging


def rent_house_list(request):

    rent_house_list = RentHouse.obs.get_queryset().filter(status=2, audit_status=2)

    if request.method == 'POST':
        area = request.POST.get('area', '')
        price = request.POST.get('price', '')
        waytorent = request.POST.get('waytorent', '')
        start_price = request.POST.get('start_price', '')
        end_price = request.POST.get('end_price', '')

        print request.POST
        if area and area != u'不限':
            rent_house_list = rent_house_list.filter(area__icontains=area)
        
        if start_price:
            rent_house_list = rent_house_list.filter(rent__gte=start_price)
        
        if end_price:
            rent_house_list = rent_house_list.filter(rent__lte=end_price)

        if not start_price and not end_price and price and price != u'不限':
            price_list = price.split('-')
            start_price = price_list[0]
            end_price = price_list[1] if len(price_list) > 1 else 0
            if not end_price:
                rent_house_list = rent_house_list.filter(rent__lte=int(start_price))
            else:
                rent_house_list = rent_house_list.filter(
                    rent__gte=int(start_price),
                    rent__lte=int(end_price),
                )
        if waytorent == u'整租':
            rent_house_list = rent_house_list.filter(lease=0)
        elif waytorent == u'合租':
            rent_house_list = rent_house_list.filter(lease=1)
        print rent_house_list
        tmp = loader.get_template('frontend/load-findToRent.html')
        html = tmp.render({'rent_houses': rent_house_list})
        return JsonResponse({'html': html})

    context = {
        'module': 'rent_house',
        'rent_houses': rent_house_list,
    }

    return render(request, 'frontend/03-findToRent.html', context)


@csrf_exempt
def rent_house_meet_create(request):
    try:
        with transaction.atomic():
            c_user = request.session.get('c_user', {})
            profile = Profile.obs.get_queryset().filter(pk=c_user.get('id', 0)).first()

            rent_house_id = request.POST.get('rent_house_id', 0)
            select_date = request.POST.get('select_date', '')
            meet_time = datetime.datetime.strptime(select_date, "%Y-%m-%d")
            rent_house = RentHouse.objects.get(pk=rent_house_id)
            rent_house_meet, _ = RentHouseMeet.objects.get_or_create(
                user=profile.user,
                rent_house=rent_house
            )
            rent_house_meet.meet_time = meet_time
            rent_house_meet.save()

    except Exception as e:
        logging.error(e)
        return JsonResponse({'error_code': 1, 'error_msg': '预约失败'})

    return JsonResponse({'error_code': 0, 'error_msg': '已接受预约工作人员会在一个工作日内协助完成预约。'})

website/templates/frontend/02-1-roomResource-2.html
{% extends 'frontend/base.html' %}

{% block title %}
房源列表
{% endblock %}

    {% block style %}
    <link rel="stylesheet" href="/static/website/css/02-1-roomResource-1.css">
    <link rel="stylesheet" href="/static/website/css/03-findToRent.css">
    {% endblock %}

{% block container %}

<div class="user">
    <img src="/static/website/images/member-bg.jpg" alt="">
</div>

<div class="howToFind banxin">
    <ul class="clearfix">
        <li><a href="{% url 'website:housing_resources_list' %}">立即找房</a></li>
        <li class="active"><a href="{% url 'website:housing_resources_map_list' %}">地图找房</a></li>
    </ul>
</div>
<!-- <div class="roomlist"></div> -->
<div id="map_container" style="width:100%; min-height:600px;min-width:1200px"></div>
{% endblock %}

{% block script %}
<script charset="utf-8" src="{{ qq_map_api_url }}"></script>
<script>
  var lng = {% if not housing_resources or housing_resources.lng == 0.0000000 %}114.30{% else %}{{ housing_resources.lng }}{% endif %};
  var lat = {% if not housing_resources or housing_resources.lat == 0.0000000 %}30.60{% else %}{{ housing_resources.lat }}{% endif %};

  var map = []

  var center = new qq.maps.LatLng(lat, lng);
  var map = new qq.maps.Map(document.getElementById("map_container"),{
    center:center,
    zoom:14
  });
</script>
{% endblock %}

website/templates/frontend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="keywords" content="租房,公寓,房租,租房价格,租房优惠,房屋出租,武汉租房 武汉公寓 武汉房租价格 武汉租房优惠 武汉房屋出租,汉口租房 汉口公寓,汉口房租,汉口租房价格,汉口租房优惠,汉口房屋出租,汉阳租房,汉阳公寓,汉阳房租,汉阳租房价格,汉阳租房优惠,汉阳房屋出租,武昌租房,武昌公寓,武昌房租,武昌租房价格,武昌租房优惠,武昌房屋出租">
    <meta name="description" content="武汉租房无中介费用，全真实房源">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="/static/website/images/logopic.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="/static/website/images/logopic.ico" type="image/x-icon">
    <link rel="stylesheet" href="/static/admin/plugins/select2/select2.min.css">
    <link rel="stylesheet" href="/static/website/css/base.css">
    {% block style %}
    {% endblock %}
</head>
<body {% block bodyclass %}{% endblock %}>
    <header class="wrap">
        <div class="banxin welcome clearfix">
            <div class="wel_left fl">
                <span class="white">欢迎来到租房网！更多房源选择任您挑选！请选择您的位置：</span>
                <select class="city white" name="city" id="">
                    <option value="武汉" selected>武汉</option>
                </select>
            </div>
            <div class="wel_right fr">
                <a class="white" href="javascript:void(0)">收藏本站 |</a>
                <a class="white" href="javascript:void(0)">设为首页 |</a>
                {% if request.session.c_user %}
                    <a class="white" href="{% url 'website:user_index' %}">{{request.session.c_user.user_name}}
                    </a>
                    <a class="white" href="{% url 'website:login_out' %}"> | 注销</a>
                {% else %}
                    <a class="white" href="{% url 'website:home_login' %}">登录 |</a>
                    <a class="white" href="{% url 'website:home_register' %}">注册 </a>
                {% endif %}
            </div>
        </div>
    </header>
    <!--nav begin-->
    <nav class="wrap">
        <div class="banxin nav clearfix">
            <a class="logo fl" href="javascript:void(0)">
                <img src="/static/website/images/LOGO.png" alt="">
            </a>
            <ul class="nav_items fl clearfix">
                <li class="fl"><a href="/">首页</a></li>
                <li class="fl">
                    <a href="{% url 'website:housing_resources_list' %}">房源信息</a>
                </li>
                <li class="fl">
                    <a href="{% url 'website:rent_house_list' %}">求租信息</a>
                </li>
<!--                 <li class="fl">
                    <a href="javascript:void(0)">生活馆</a>
                </li> -->
                <li class="fl">
                {% if request.session.c_user %}
                    <a href="{% url 'website:user_index' %}">用户中心</a>
                {% else %}
                    <a href="{% url 'website:home_login' %}">注册登录</a>
                {% endif %}
                </li>
            </ul>
            <div class="hot-line fr">
<!--            <div class="p_number green">
                    <b></b>400-6789-888
                </div>
                <div class="p_time fr">看房热线：<span class="green">08:00 - 21:00</span></div> -->
                <img src="/static/website/images/QRcode.png" alt="公众号二维码">
                <p align="center">联系我们</p>
            </div>
        </div>
    </nav>

    <!--nav end-->
    {% block container %}
    {% endblock %}

    <!--footer begin-->
    <div class="footer wrap">
        <img src="/static/website/images/footer.png" alt="">
        <div class="company banxin">
            <span class="service">SERVICE</span>
            电话咨询服务电话：<span class="number green">400-1371-365</span>
            <span class="right">&reg 2017 Zuke</span>
        </div>
    </div>

    <!--footer end-->
    <script src="//at.alicdn.com/t/font_ydrr42zlcvea5rk9.js"></script>
    <script src="/static/website/js/jquery-3.2.1.js"></script>
    <script src="/static/website/js/nav.js"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

website/templates/frontend/login.html
{% extends 'frontend/base.html' %}

{% block title %}
首页
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="/static/website/css/05-1-login.css">
{% endblock %}

{% block container %}

<div class="mask-bg wrap">
    <img src="/static/website/images/login-bg.jpg" alt="">
    <div class="login">
        <h1 class="green" align="center">登陆</h1>
        <p class="user-name" align="center"><input type="text" id="user_name" name="user_name" placeholder="手机号/邮箱"></p>
        <p class="pwd" align="center"><input type="password" id="login_password" name="login_password" placeholder="密码"></p>
        <div class="register-code clearfix">
            <div class="fl">
                <input id="auto-login" type="checkbox">&nbsp<span>三天内自动登陆</span>
            </div>
            <div class="fr">
                <a href="{% url 'website:home_register' %}">立即注册</a>&nbsp
                <a href="{% url 'website:reset_pwd' %}">忘记密码</a>
            </div>
        </div>
        <p class="submit"><input class="white" type="submit" id="subLogin" name="subLogin" value="登 录" onclick="login();"></p>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="/static/website/js/jquery.cookie.js"></script>
<script src="/static/website/js/jquery.base64.js"></script>
<script src="/static/website/js/05-1-login.js"></script>
<script>
    function login(){
    var userName = $('#user_name').val();
    if(userName == ''){
        alert("请输入用户名。");
        $('#user_name').select();
        return;
    }
    var userPass = $('#login_password').val();
    if(userPass == ''){
        alert("请输入密码。");
        $('#login_password').select();
        return;
    }

    $.ajax({
        url: '{% url "website:home_login" %}',
        async: false,
        type: 'post',
        data: {
            userName: userName,
            userPass: userPass
        },
        success: function(res, status){
            if(!res.error_code){
                location.href = '{{domain}}'
            }else{
                alert(res.error_msg)
            }
        },
        error: function(res, status){
            alert('登陆失败')
        }
    })

    //判断是否选中复选框，如果选中，添加cookie
    var checked = document.getElementById("auto-login").checked; //获取“是否记住密码”复选框
    if(checked) {
        //添加cookie
        setCookie();
    }
}

</script>
{% endblock %}